### ISSUE TITLE
GPT-4 support

### ISSUE THREAD

**Issue by danielphan2003** [L4TTiCe/BotForge#14]
As issue titled

**Comment by L4TTiCe** [comment]
I have just released v1.3.2 with support for multiple models, But as I don't have access to GPT-4 API personally, I am not able text if it works as intended. Can anyone with GPT-4 API check if GPT 4 shows up as an option under Advanced API Settings?

**Comment by danielphan2003** [comment]
It's not showing up even though I'm having GPT4 access on the web
![Screenshot_20230509-085623_BotForge.png](https://user-images.githubusercontent.com/34669737/236974641-86b4458a-3b33-428c-b2cb-f128fc632748.png)

**Comment by L4TTiCe** [comment]
Do you have GPT-4 API access? I think having ChatGPT Pro subscription does not automatically give GPT-4 API access. So, even with ChatGPT Pro subscription, access to GPT-4's API through the waitlist is required.
